"""
Content API Routes - Thin handlers that delegate to ContentController.
Preserves all endpoints and functionality from routes/content.py
"""

from fastapi import APIRouter, Response
from core.services.ai.job_runner import JobStatus
from core.api.schemas.content_schemas import AHSRequest, RemedyRequest
from core.api.controllers.content_controller import ContentController

router = APIRouter()

@router.post("/v1/contentGenerationForAHS", response_model=JobStatus, status_code=202)
async def content_generation_for_ahs(payload: AHSRequest):
    """Generate AHS (After Hour Session) content. Delegates to ContentController."""
    return await ContentController.create_ahs_content(payload)

@router.post("/v1/contentGenerationForRemedies", response_model=JobStatus, status_code=202)
async def content_generation_for_remedies(payload: RemedyRequest):
    """
    Generate remediation content using Remedy Agent → Content Agent flow.
    Delegates to ContentController.
    """
    return await ContentController.create_remedy_content(payload)

@router.get("/v1/jobs/{job_id}", response_model=JobStatus)
async def job_status(job_id: str):
    """Get job status. Delegates to ContentController."""
    return await ContentController.get_job_status(job_id)

@router.get("/v1/debug/jobs")
async def debug_jobs():
    """Debug endpoint to see all jobs in memory. Delegates to ContentController."""
    return await ContentController.get_debug_jobs()

@router.get("/v1/debug/jobs/{job_id}")
async def debug_job_status(job_id: str):
    """Debug endpoint to check job status across all sources. Delegates to ContentController."""
    return await ContentController.get_debug_job_status(job_id)

@router.get("/v1/sessions/{session_id}/afterHourSession")
async def get_after_hour_session(session_id: str):
    """Get after hour session data. Delegates to ContentController."""
    return await ContentController.get_after_hour_session(session_id)

@router.get("/v1/jobs/{job_id}/content")
async def job_content(job_id: str, response: Response):
    """
    Return generated content for a job once completed.
    Delegates to ContentController.
    """
    return await ContentController.get_job_content(job_id, response)

@router.get("/v1/remedyJobs/{job_id}/plans")
async def get_remedy_plans(job_id: str):
    """
    Get the remediation plans generated by a completed remedy job.
    Delegates to ContentController.
    """
    return await ContentController.get_remedy_plans(job_id)

@router.get("/v1/jobs/{job_id}/aggregate")
async def job_aggregate(job_id: str):
    """
    Aggregated parent job view: plans, child jobs, content specs, and RAG outputs.
    Delegates to ContentController.
    """
    return await ContentController.get_job_aggregate(job_id)

@router.get("/v1/remedyJobs/{job_id}/content")
async def get_remedy_content(job_id: str):
    """
    Get the final content generated by Content Agent for this remedy job.
    Delegates to ContentController.
    """
    return await ContentController.get_remedy_content_by_job(job_id)